# Generated by Django 4.0.3 on 2022-03-08 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('img1', models.ImageField(upload_to='media/img')),
                ('resume', models.FileField(upload_to='media/resume')),
                ('mail', models.TextField(null=True)),
                ('telegram', models.TextField(null=True)),
                ('phone', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('job', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='My_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('lang1', models.CharField(max_length=200, null=True)),
                ('lang2', models.CharField(max_length=200, null=True)),
                ('lang3', models.CharField(max_length=200, null=True)),
                ('lang4', models.CharField(max_length=200, null=True)),
                ('lang5', models.CharField(max_length=200, null=True)),
                ('lang6', models.CharField(max_length=200, null=True)),
                ('link_git', models.TextField(null=True)),
                ('img1', models.ImageField(upload_to='media/img')),
                ('img2', models.ImageField(upload_to='media/img')),
            ],
        ),
    ]
