# Generated by Django 4.0.3 on 2022-03-08 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='my_work',
            old_name='link_git',
            new_name='link_github',
        ),
        migrations.AddField(
            model_name='my_work',
            name='link_site',
            field=models.TextField(null=True),
        ),
    ]
