# Generated by Django 4.0.3 on 2022-03-08 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_rename_link_git_my_work_link_github_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='description2',
            field=models.TextField(null=True),
        ),
    ]
